name: python config unittest

on:
  push:
    paths:
      - 'p_terraformer/config/*'
jobs:
  localstack-start:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      - name: install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install awscli-local
        run: |
          pip install awscli
      - name: aws cli version
        run: |
          awslocal secretsmanager create-secret --name test --secret-string '{"test":"test"}'
      - name: cmd unit test
        run: |
          python -m unittest discover -s ./p_terraformer/tests/test_cmd -p "*.py"
