name: python config unittest

on:
  push:
    paths:
      - 'p_terraformer/config/*'
jobs:
  cmd-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      - name: install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start localstack
        run: |
          docker-compose up -d localstack
      # - name: cmd unit test
      #   run: |
      #     python -m unittest discover -s ./p_terraformer/tests/test_cmd -p "*.py"
