name: python config unittest

on:
  push:
    paths:
      - 'p_terraformer/config/*'
jobs:
  config-unittest:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      - name: install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install awscli-local awscli
        run: |
          pip install awscli-local
          pip install awscli
      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: "hogehoge"
          AWS_SECRET_ACCESS_KEY: "hogehoge"
        run: |
          aws configure --profile default set aws_access_key_id=$AWS_ACCESS_KEY_ID
          aws configure --profile default set aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
          aws configure --profile default set region=us-east-1
      - name: add secret
        run: |
          awslocal secretsmanager create-secret --name test --secret-string '{"test":"test"}'  --endpoint-url=http://localhost:4566
      - name: config unit test
        run: |
          python -m unittest discover -s ./p_terraformer/tests/test_config -p "*.py"
